### ISSUE TITLE
Fatal error when cloning

### ISSUE THREAD

**Issue by laurenlucero** [amorriscode/advent-of-code#14]
I am trying to use your template but get an error when cloning. Please advise. Thank you!
```
gh repo clone laurenlucero/AoC21
Cloning into 'AoC21'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit status 128
```

**Comment by amorriscode** [comment]
Hey @laurenlucero, have you set up your SSH keys on GitHub? There's [a document about this error](https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey) but I don't believe it's anything related to my repo (it's public after all).

Alternatively, you can try using GitHub's template button:

![image](https://user-images.githubusercontent.com/16005567/144288897-bdb5c9a7-2862-4236-a194-d139f9b37f29.png)

It's on the main repo page right next to the "Code" button:

![image](https://user-images.githubusercontent.com/16005567/144289346-b87895a9-57e7-457b-8cb5-70402d4dfa63.png)

Let me know if that helps!

**Comment by amorriscode** [comment]
@laurenlucero I think your GitHub CLI command is incorrect. It looks like you're trying to clone `laurenlucero/AoC21` which is _not_ actually a valid GitHub repo (see: https://github.com/laurenlucero/AoC21). You'd have to fork this repo to `laurenlucero/AoC21` first.

If you want to clone this repo you can try this command:

```bash
git clone git@github.com:amorriscode/advent-of-code.git
```

Alternatively, you can try using GitHub's template button:

![image](https://user-images.githubusercontent.com/16005567/144288897-bdb5c9a7-2862-4236-a194-d139f9b37f29.png)

It's on the main repo page right next to the "Code" button:

![image](https://user-images.githubusercontent.com/16005567/144289346-b87895a9-57e7-457b-8cb5-70402d4dfa63.png)

Let me know if that helps!

**Comment by laurenlucero** [comment]
Thank you, I was able to resolve by following the document about this error!
